# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar testes
      run: |
        pytest
  
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform -chdir=infra init

      - name: Aplicar Terraform e salvar IP
        run: |
          # Aplica a infraestrutura
          terraform -chdir=infra apply -auto-approve

          # Salva o IP público da instância em um arquivo
          terraform -chdir=infra output -raw public_ip > public_ip.txt

      - name: Upload do IP como Artifact
        uses: actions/upload-artifact@v3
        with:
          name: public-ip
          path: public_ip.txt

  deploy:
    runs-on: ubuntu-latest
    needs: terraform # Garante que este job só roda depois do 'terraform'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download do IP como Artifact
        uses: actions/download-artifact@v3
        with:
          name: public-ip

      - name: Criar arquivo de chave
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Conectar via SSH
        run: |
          # Lê o IP do arquivo e remove espaços em branco
          EC2_IP=$(cat public_ip.txt | tr -d '[:space:]')
          
          # Conecta-se via SSH usando o IP
          ssh -i ~/.ssh/id_rsa ec2-user@$EC2_IP
        shell: bash