# .github/workflows/ci.yml
name: CI Pipeline Web

# O pipeline será executado em cada push e pull request para o branch 'main'.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define um job para construir e testar a aplicação.
jobs:
  build-test:
    # O job será executado na última versão do Ubuntu.
    runs-on: ubuntu-latest

    # Os passos (steps) para a execução do job.
    steps:
      - name: Checkout do código
        # Usa a action 'actions/checkout' para clonar o repositório.
        uses: actions/checkout@v3

      - name: Configurar Node.js
        # Configura o ambiente Node.js para rodar os testes.
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências de teste
        # Instala o Jest para rodar os testes.
        # Aqui, você precisaria de um arquivo package.json com a dependência
        # do Jest. Como não temos um, instalamos diretamente.
        run: npm install jest

      - name: Executar testes de frontend
        # Executa os testes JavaScript com o Jest. O Jest busca
        # automaticamente por arquivos com o padrão .test.js
        run: npx jest
