name: CI Pipeline Web

# O pipeline será executado em cada push e pull request para o branch 'main'.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Trabalhos da aplicação.
jobs:
  build-test:
    runs-on: ubuntu-latest

    # Passos que serão executados.
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências de teste
        # Instala o Jest.
        run: npm install jest

      - name: Executar testes de frontend
        # Executa os testes JavaScript com o Jest.
        run: npx jest

      - name: Build do site para a pasta dist
        run: |
          mkdir dist
          cp index.html dist/index.html

      # --- Etapa de Implantação Contínua (CD) ---
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        id: init
        run: terraform init
        working-directory: ./infra

      - name: Planejar a implantação
        id: plan
        run: terraform plan
        working-directory: ./infra

      - name: Aplicar a infraestrutura simulada
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./infra

      - name: Instalar e iniciar servidor web local
        run: |
          npm install http-server -g
          npx http-server ./dist &
          echo "Servidor rodando em http://localhost:8080"

      - name: Exibir a URL do site implantado
        run: |
          echo "Site implantado com sucesso no caminho: $(terraform output -raw site_url)"
        working-directory: ./infra