# .github/workflows/ci.yml
name: CI Pipeline

# Quando o pipeline será executado.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Tarefas que serão executadas.
jobs:
  build-test:
    runs-on: ubuntu-latest

    # Passo a passo que deve ser executado.
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar testes
      run: |
        pytest
  
  