# .github/workflows/terraform.yml
name: terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform com provedor Docker
        run: terraform -chdir=$TF_DIR init

      - name: Aplicar Terraform e executar o contêiner
        # O Terraform aplicará as configurações, construindo a imagem e
        # executando o contêiner. O resultado da execução do script será exibido
        # diretamente no log da pipeline.
        run: terraform -chdir=$TF_DIR apply -auto-approve

