# .github/workflows/terraform.yml

name: Terraform Provisioning

on:
  workflow_dispatch:  # Permite a execução manual

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform -chdir=infra init

      - name: Aplicar Terraform
        run: terraform -chdir=infra apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: terraform # Garante que este job só roda depois do 'terraform'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Criar arquivo de chave
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Conectar via SSH
        run: |
          # Use a chave para fazer SSH
          ssh -i ~/.ssh/id_rsa ec2-user@your-instance-ip