# .github/workflows/terraform.yml
name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    # Define o diretório de trabalho do Terraform.
    env:
      TF_DIR: infra

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform -chdir=$TF_DIR init

      - name: Aplicar Terraform
        # O comando 'apply' agora criará o contêiner e capturará a saída.
        run: terraform -chdir=$TF_DIR apply -auto-approve